# Generated by Django 5.2.6 on 2025-10-21 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('dispute', 'Dispute'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('skill1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_exchanges', to='main.skill')),
                ('skill2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_exchanges', to='main.skill')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
                'ordering': ['-start_date'],
            },
        ),
    ]
