# Generated by Django 5.2.6 on 2025-10-25 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userskill',
            old_name='role',
            new_name='skill_type',
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill', 'skill_type')},
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='proficiency',
        ),
    ]
